name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SEMANTIC_BOT_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_BOT_PRIVATE_KEY }}

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci

      - name: Release
        run: HUSKY=0npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
